name: simple_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - scipy
  - pip
  # list packages to be installed via pip:
  - pip:
    - mixsea
    # install a local package in developer mode
    - "-e /Users/gunnar/Projects/python/gvpy"
